App_Areas/Admin/Controllers/CustomerController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectricsOnlineWebApp.Areas.Admin.Controllers
{
    public class CustomerController : BaseController
    {
        public CustomerController(){
            Mapper.Initialize(cfg => {
                cfg.CreateMap<Customer, ElectricsOnlineWebApp.Models.Customer>();
            });
        }

        // GET: Admin/Customer
        public ActionResult Index()
        {
            var customers = _ctx.Customers.ToList();
            var model = Mapper.Map<IEnumerable<Customer>, IEnumerable<ElectricsOnlineWebApp.Models.Customer>>(customers);
            return View("Index", model);
        }

        // GET: Admin/Customer/Details/5
        public ActionResult Details(int id)
        {
            var customer = _ctx.Customers.FirstOrDefault(c => c.CID == id);
            var model = Mapper.Map<Customer, ElectricsOnlineWebApp.Models.Customer>(customer);
            return View(model);
        }

        // GET: Admin/Customer/Delete/5
        public ActionResult Delete(int id)
        {
            var customer = _ctx.Customers.FirstOrDefault(c => c.CID == id);
            _ctx.Customers.Remove(customer);
            _ctx.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

App_Areas/Admin/Controllers/OrderController.cs
using AutoMapper;
using ElectricsOnlineWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectricsOnlineWebApp.Areas.Admin.Controllers
{
    public class OrderController : BaseController
    {
        public OrderController()
        {
            Mapper.Initialize(cfg => {
                cfg.CreateMap<Order, OrderModel>();
            });
        }

        // GET: Admin/Order
        public ActionResult Index()
        {
            var orders = _ctx.Orders;
            var model = Mapper.Map<IEnumerable<Order>, IEnumerable<OrderModel>>(orders);
            return View(model);
        }

        // GET: Admin/Order/Details/5
        public ActionResult Details(int id)
        {
            var order = _ctx.Orders.FirstOrDefault(o => o.OrderID == id);
            var model = Mapper.Map<OrderModel>(order);
            return View(model);
        }
    }
}

App_Areas/Admin/Controllers/ProductController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectricsOnlineWebApp.Areas.Admin.Controllers
{
    public class ProductController : BaseController
    {
        public ProductController()
        {
            Mapper.Initialize(cfg => {
                cfg.CreateMap<Product, Models.Product>();
                cfg.CreateMap<Models.Product, Product>();
            });

            ViewBag.Suppliers = _ctx.Suppliers;
        }
        // GET: Admin/Product
        public ActionResult Index()
        {
            var products = _ctx.Products;
            var model = Mapper.Map<IEnumerable<Product>, IEnumerable<Models.Product>>(products);
            return View(model);
        }

        private Models.Product _getProduct(int id)
        {
            var product = _ctx.Products.FirstOrDefault(p => p.PID == id);
            var model = Mapper.Map<Product, Models.Product>(product);
            return model;
        }

        // GET: Admin/Product/Details/5
        public ActionResult Details(int id)
        {
            return View(_getProduct(id));
        }

        // GET: Admin/Product/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Product/Create
        [HttpPost]
        public ActionResult Create(Models.Product model)
        {
            try
            {

                // TODO: Add insert logic here
                var product = new Product
                {
                    PName = model.PName,
                    Brand = model.Brand,
                    Category = model.Category,
                    Description = model.Description,
                    ROL = model.ROL,
                    SID = model.SID,
                    UnitPrice = model.UnitPrice,
                    UnitsInStock = model.UnitsInStock
                };
                _ctx.Products.Add(product);
                _ctx.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return View(model);
            }
        }

        // GET: Admin/Product/Edit/5
        public ActionResult Edit(int id)
        {
            return View(_getProduct(id));
        }

        // POST: Admin/Product/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Models.Product model)
        {
            try
            {
                // TODO: Add update logic here
                Product p = _ctx.Products.FirstOrDefault(pr => pr.PID == model.PID);

                p.UnitPrice = model.UnitPrice;
                p.UnitsInStock = model.UnitsInStock;
                p.SID = model.SID;
                p.Brand = model.Brand;
                p.Description = model.Description;
                p.Category = model.Category;

                _ctx.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                
                return View(model);
            }
        }

        // GET: Admin/Product/Delete/5
        public ActionResult Delete(int id)
        {
            var product = _ctx.Products.FirstOrDefault(p => p.PID == id);
            return RedirectToAction("Index");
        }
    }
}

App_Areas/Admin/Controllers/StockController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectricsOnlineWebApp.Areas.Admin.Controllers
{
    public class StockController : BaseController
    {

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Chart()
        {
            var units = new List<int>();
            var rol = new List<int>();
            var labels = new List<string>();
            foreach (var i in _ctx.Products)
            {
                units.Add(i.UnitsInStock);
                rol.Add(i.ROL);
                labels.Add(i.PName);
            }
            List<object> data = new List<object> { new {
                label = "Units in Stock",
                backgroundColor = "rgba(255, 99, 132, 0.6)",
                data = units
            }, new {
                label = "Re-Order-Level",
                backgroundColor = "rgba(153, 102, 255, 0.6)",
                data = rol
            }, labels};

            var result = Json(data.ToArray(), JsonRequestBehavior.AllowGet);
            return result;
        }

        private string _randomColor()
        {
            Random randomGen = new Random();
            KnownColor[] names = (KnownColor[])Enum.GetValues(typeof(KnownColor));
            KnownColor randomColorName = names[randomGen.Next(names.Length)];
            Color c = Color.FromKnownColor(randomColorName);
            return "#" + c.R.ToString("X2") + c.G.ToString("X2") + c.B.ToString("X2");
        }
    }
}

App_Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Electrics Online</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("scripts", required: false)

</head>
<body>
    <div class="navbar navbar-theme navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Admin Panel", "Index", "Product", new { area = "Admin" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Suppliers", "Index", "Supplier", null, null)</li>
                    <li>@Html.ActionLink("Customers", "Index", "Customer", null, null)</li>
                    <li>@Html.ActionLink("Orders", "Index", "Order", null, null)</li>
                    <li>@Html.ActionLink("Stocks", "Index", "Stock", null, null)</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Shop", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Logout", "Logout", "Account", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Electrics Online</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>